### ISSUE TITLE
No member named '__rip' in '__darwin_arm_thread_state64'

### ISSUE THREAD

**Issue by im-aditya** [f111fei/react-native-unity-view#31]
I am trying to compile the project on xcode 9 and I am getting this error: 

<img width="1121" alt="screen shot 2018-07-22 at 12 35 54 pm" src="https://user-images.githubusercontent.com/3098218/43043209-d8c86454-8dab-11e8-8911-d414d43de676.png">

**Comment by Stalder** [comment]
I don't think it somehow related to this library. I had the same exception in project without this lib. Workaround for this is to return NULL instead of expresion, that cause error

**Comment by JanOwiesniak** [comment]
Just a short side note: You should build with XCode 10.1 or higher, otherwise you can not (without any hacks) distribute your app to the Apple App Store. XCode 9.x does not include iOS 12.x SDK (which is mandatory by now)

![Screenshot 2019-03-15 at 10 11 07](https://user-images.githubusercontent.com/213214/54420614-c14ffa80-470a-11e9-9eae-110662e2d14b.png)

- https://developer.apple.com/ios/submit/

**Comment by im-aditya** [comment]
Yes, I have already updated XCode.
Thanks
