### ISSUE TITLE
Library doesn't work with Unity version 2018.3.0f2

### ISSUE THREAD

**Issue by MarcosRenato266** [f111fei/react-native-unity-view#110]
`> Task :react-native-unity-view:compileDebugJavaWithJavac FAILED
C:\dvida projects\github\dvida-mug\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityUtils.java:10: error: package com.unity3d.player does not exist
import com.unity3d.player.UnityPlayer;
                         ^
C:\dvida projects\github\dvida-mug\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityUtils.java:25: error: cannot find symbol
    private static UnityPlayer unityPlayer;
                   ^
  symbol:   class UnityPlayer
  location: class UnityUtils
C:\dvida projects\github\dvida-mug\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityUtils.java:32: error: cannot find symbol
    public static UnityPlayer getPlayer() {
                  ^
  symbol:   class UnityPlayer
  location: class UnityUtils
C:\dvida projects\github\dvida-mug\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityView.java:7: error: package com.unity3d.player does not exist
import com.unity3d.player.UnityPlayer;
                         ^
C:\dvida projects\github\dvida-mug\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityView.java:15: error: cannot find symbol
    private UnityPlayer view;
            ^
  symbol:   class UnityPlayer
  location: class UnityView
C:\dvida projects\github\dvida-mug\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityView.java:21: error: cannot find symbol
    public void setUnityPlayer(UnityPlayer player) {
                               ^
  symbol:   class UnityPlayer
  location: class UnityView
C:\dvida projects\github\dvida-mug\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityUtils.java:62: error: cannot find symbol
                unityPlayer = new UnityPlayer(activity);
                                  ^
  symbol: class UnityPlayer
C:\dvida projects\github\dvida-mug\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityUtils.java:91: error: cannot find symbol
        UnityPlayer.UnitySendMessage(gameObject, methodName, message);
        ^
  symbol:   variable UnityPlayer
  location: class UnityUtils
8 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-unity-view:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.`

Already try solutions from : https://github.com/f111fei/react-native-unity-demo/issues/21

But cant solved it :/
